In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"../data/raw/supply_chain_dataset.csv")
df.head()

,Product_ID,Warehouse,Order_Date,Shipment_Date,Lead_Time,Demand_Forecast,Inventory_Level,Stockout_Flag,Backorder_Flag,Supplier_ID,Order_Quantity,Shipment_Quantity,Product_Category,Product_Price,Customer_ID,Order_Priority
0,8270,A,1/1/2023,1/2/2023,8,839,481,0,0,397,98,40,Clothing,387.89,2014,High
1,1860,C,1/1/2023,1/2/2023,8,351,332,0,1,483,52,35,Furniture,891.03,6805,High
2,6390,C,1/1/2023,1/2/2023,5,398,156,0,0,160,34,43,Food,933.21,3833,Medium
3,6191,A,1/1/2023,1/2/2023,5,972,418,1,0,161,32,45,Electronics,628.57,3640,Medium
4,6734,D,1/1/2023,1/2/2023,3,529,428,0,0,325,44,41,Electronics,70.33,9297,Medium

In [3]:
#EDA

In [4]:
df.shape

(9000, 16)

In [5]:
df.columns

Index(['Product_ID', 'Warehouse', 'Order_Date', 'Shipment_Date', 'Lead_Time',
       'Demand_Forecast', 'Inventory_Level', 'Stockout_Flag', 'Backorder_Flag',
       'Supplier_ID', 'Order_Quantity', 'Shipment_Quantity',
       'Product_Category', 'Product_Price', 'Customer_ID', 'Order_Priority'],
      dtype='object')

In [6]:
df.isna().sum()

Product_ID           0
Warehouse            0
Order_Date           0
Shipment_Date        0
Lead_Time            0
Demand_Forecast      0
Inventory_Level      0
Stockout_Flag        0
Backorder_Flag       0
Supplier_ID          0
Order_Quantity       0
Shipment_Quantity    0
Product_Category     0
Product_Price        0
Customer_ID          0
Order_Priority       0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product_ID         9000 non-null   int64
 1   Warehouse          9000 non-null   object
 2   Order_Date         9000 non-null   object
 3   Shipment_Date      9000 non-null   object
 4   Lead_Time          9000 non-null   int64
 5   Demand_Forecast    9000 non-null   int64
 6   Inventory_Level    9000 non-null   int64
 7   Stockout_Flag      9000 non-null   int64
 8   Backorder_Flag     9000 non-null   int64
 9   Supplier_ID        9000 non-null   int64
 10  Order_Quantity     9000 non-null   int64
 11  Shipment_Quantity  9000 non-null   int64
 12  Product_Category   9000 non-null   object
 13  Product_Price      9000 non-null   float64
 14  Customer_ID        9000 non-null   int64
 15  Order_Priority     9000 non-null   object
dtypes: float64(1), int64(10), object(5)
memory usage: 1.1+ MB

,Product_ID,Lead_Time,Demand_Forecast,Inventory_Level,Stockout_Flag,Backorder_Flag,Supplier_ID,Order_Quantity,Shipment_Quantity,Product_Price,Customer_ID
count,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,5454.036222,4.970556,551.367222,248.182444,0.201444,0.159778,301.394333,50.296111,49.408889,503.122006,5496.182222
std,2579.234042,2.579402,259.098562,145.036179,0.405784,0.374222,115.399885,28.958419,28.754420,287.872648,2586.398894
min,1001.000000,1.000000,100.000000,0.000000,0.000000,0.000000,100.000000,1.000000,1.000000,10.140000,1000.000000
25%,3220.000000,3.000000,327.000000,123.000000,0.000000,0.000000,200.000000,25.000000,25.000000,254.502500,3282.750000
50%,5448.000000,5.000000,555.000000,246.000000,0.000000,0.000000,304.000000,51.000000,49.000000,497.550000,5482.000000
75%,7675.500000,7.000000,773.000000,375.000000,0.000000,0.000000,401.000000,76.000000,74.000000,755.322500,7704.250000
max,9998.000000,9.000000,999.000000,499.000000,2.000000,2.000000,499.000000,99.000000,99.000000,999.890000,9998.000000

In [9]:
print(df['Stockout_Flag'].value_counts())
print()
print(df['Backorder_Flag'].value_counts())

Stockout_Flag
0    7204
1    1779
2      17
Name: count, dtype: int64

Backorder_Flag
0    7588
1    1386
2      26
Name: count, dtype: int64

In [10]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Shipment_Date'] = pd.to_datetime(df['Shipment_Date'])

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product_ID         9000 non-null   int64
 1   Warehouse          9000 non-null   object
 2   Order_Date         9000 non-null   datetime64[ns]
 3   Shipment_Date      9000 non-null   datetime64[ns]
 4   Lead_Time          9000 non-null   int64
 5   Demand_Forecast    9000 non-null   int64
 6   Inventory_Level    9000 non-null   int64
 7   Stockout_Flag      9000 non-null   int64
 8   Backorder_Flag     9000 non-null   int64
 9   Supplier_ID        9000 non-null   int64
 10  Order_Quantity     9000 non-null   int64
 11  Shipment_Quantity  9000 non-null   int64
 12  Product_Category   9000 non-null   object
 13  Product_Price      9000 non-null   float64
 14  Customer_ID        9000 non-null   int64
 15  Order_Priority     9000 non-null   object
dtypes: datetime64[ns](2), float64(1), int64(10), object(3)
memory usage: 1.1+ MB